version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.1
    container_name: redpanda
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1                # Batasi hanya pakai 1 CPU core
      - --memory 512M          # Batasi RAM (Sesuaikan: 512M atau 1G)
      - --reserve-memory 0M    # Jangan pesan memori tambahan
      - --node-id 0
      - --check=false          # Lewati pengecekan hardware standar produksi
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
    ports:
      - "19092:19092"          # Port untuk akses dari luar Docker (Konduktor/Go Local)
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info"]
      interval: 10s
      timeout: 5s
      retries: 5

  console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    entrypoint: /bin/sh
    command: -c "echo \"kafka: { brokers: ['redpanda:9092'] }\" > /tmp/config.yml; /app/console --config.filepath /tmp/config.yml"
    ports:
      - "8080:8080"            # Akses UI via browser di localhost:8080
    depends_on:
      redpanda:
        condition: service_healthy